DOWNLOAD_VERSION: 0.8.3

ALERT_CLASS:
  all: 
  ar: 
  de: 
  en: 
  es: 
  fa: 
  fr: 
  it: 
  nl: 
  pl: 
  ru: 
  tr: 
  zh_TW: 
  
ALERT:
  all: 
  ar: 
  de: 
  en: 
  es: 
  fa: 
  fr: 
  it: 
  nl: 
  pl: 
  ru: 
  tr: 
  zh_TW: 

langsorder:
- id: de
- id: en
- id: es
- id: fr
- id: it
- id: nl
- id: pl
- id: ru
- id: tr
- id: zh_TW
- id: ar
- id: fa

langs:
  ar: ألعربية
  de: Deutsch
  en: English
  es: Español
  fa: فارسی
  fr: Français
  it: Italiano
  nl: Nederlands
  pl: Polski
  ru: Русский
  tr: Türkçe
  zh_TW: ‪繁體中文‬

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider
