DOWNLOAD_VERSION: 0.8.1
ALERT_CLASS: 
ALERT: 

langs:
  fr: Fran√ßais
  en: English
  
section:
  index:
    en: 
    fr: 
  about:
    en: about
    fr: a-propos
  bitcoin-for-developers:
    en: bitcoin-for-developers
    fr: bitcoin-pour-developpeurs
  bitcoin-for-enthusiasts:
    en: bitcoin-for-enthusiasts
    fr: bitcoin-pour-passionnes
  bitcoin-for-individuals:
    en: bitcoin-for-individuals
    fr: bitcoin-pour-particuliers
  bitcoin-for-organizations:
    en: bitcoin-for-organizations
    fr: bitcoin-pour-organisations
  bitcoin-for-press:
    en: bitcoin-for-press
  choose-your-wallet:
    en: choose-your-wallet
    fr: choisir-votre-porte-monnaie
  community:
    en: community
    fr: communaute
  development:
    en: development
    fr: developpement
  download:
    en: download
    fr: telecharger
  foundation:
    en: foundation
    fr: fondation
  how-it-works:
    en: how-it-works
    fr: comment-ca-marche
  resources:
    en: resources
    fr: ressources
  support-bitcoin:
    en: support-bitcoin
    fr: supporter-bitcoin
  version-history:
    en: version-history
  vocabulary:
    en: vocabulary
    fr: vocabulaire
  you-need-to-know:
    en: you-need-to-know
    fr: vous-devez-savoir

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
    
aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider
