langsorder:
- id: de
- id: id
- id: en
- id: es
- id: fr
- id: it
- id: hu
- id: nl
- id: pl
- id: ru
- id: sv
- id: tr
- id: bg
- id: zh_CN
- id: zh_TW
- id: ar
- id: fa

langs:
  ar: ألعربية
  bg: български
  de: Deutsch
  en: English
  es: Español
  fa: فارسی
  fr: Français
  hu: magyar
  id: Bahasa Indonesia‬
  it: Italiano
  nl: Nederlands
  pl: Polski
  ru: Русский
  sv: Svenska
  tr: Türkçe
  zh_CN: ‪简体中文‬
  zh_TW: ‪繁體中文‬

redirects:
  /news: /en/version-history
  /clients: /en/choose-your-wallet
  /about: /en/faq
  /ar/بت-كوين-للهواة: /ar/innovation
  /ar/عن: /ar/faq
  /ar/بت-كوين-للمطورين: /ar/bitcoin-for-developers
  /ar/بت-كوين-للأفراد: /ar/bitcoin-for-individuals
  /ar/إختر-محفظتك: /ar/choose-your-wallet
  /ar/بت-كوين-للأعمال: /ar/bitcoin-for-businesses
  /ar/إختر-محفظتك: /ar/choose-your-wallet
  /ar/مجتمع: /ar/community
  /ar/تطوير: /ar/development
  /ar/تحميل: /ar/download
  /ar/كيف-يعمل: /ar/how-it-works
  /ar/مصادر: /ar/resources
  /ar/إدعم-ألبت-كوين: /ar/support-bitcoin
  /ar/مفردات: /ar/vocabulary
  /ar/تحتاج-أن-تعلم: /ar/you-need-to-know
  /fa/بیت-کوین-برای-علاقه-مندان: /fa/innovation
  /fa/درباره: /fa/faq
  /fa/بیت-کوین-برای-توسعه-دهندگان: /fa/bitcoin-for-developers
  /fa/بیت-کوین-برای-افراد: /fa/bitcoin-for-individuals
  /fa/بیت-کوین-برای-کسب-و-کار: /fa/bitcoin-for-businesses
  /fa/انتخاب-کیف-پول: /fa/choose-your-wallet
  /fa/انجمن: /fa/community
  /fa/توسعه: /fa/development
  /fa/دانلود: /fa/download
  /fa/چگونه-کار-می-کند: /fa/how-it-works
  /fa/منابع: /fa/resources
  /fa/کیف-پولتان-را-ایمن-کنید: /fa/secure-your-wallet
  /fa/حمایت-از-بیت-کوین: /fa/support-bitcoin
  /fa/واژگان: /fa/vocabulary
  /fa/آن-چه-باید-بدانید: /fa/you-need-to-know
  /ru/биткоин-разработчикам: /ru/bitcoin-for-developers
  /ru/биткоин-частным-лицам: /ru/bitcoin-for-individuals
  /ru/биткоин-бизнесу: /ru/bitcoin-for-businesses
  /ru/выберите-свой-кошелек: /ru/choose-your-wallet
  /ru/сообщество: /ru/community
  /ru/разработка: /ru/development
  /ru/загрузки: /ru/download
  /ru/как-это-работает: /ru/how-it-works
  /ru/ресурсы: /ru/resources
  /ru/поддержать-биткоин: /ru/support-bitcoin
  /ru/термины: /ru/vocabulary
  /ru/вам-нужно-знать: /ru/you-need-to-know
  /ru/описание: /ru/faq
  /ru/биткоин-энтузиастам: /ru/innovation
  /en/bitcoin-for-press: /en/press
  /de/ueber: /de/faq
  /en/about: /en/faq
  /zh_CN/about: /zh_CN/faq
  /es/acerca-de: /es/faq
  /fr/a-propos: /fr/faq
  /de/bitcoin-fuer-enthusiasten: /de/innovation
  /en/bitcoin-for-enthusiasts: /en/innovation
  /es/bitcoin-para-entusiastas: /es/innovacion
  /fr/bitcoin-pour-passionnes: /fr/innovation
  /it/bitcoin-per-appassionati: /it/innovazione
  /nl/bitcoin-voor-liefhebbers: /nl/innovatie
  /pl/bitcoin-dla-entuzjastow: /pl/innowacje

aliases:
  s_nakamoto: Satoshi Nakamoto
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  tcatm: Nils Schneider

safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: rouge
pygments:    true
markdown:    kramdown
permalink:   date

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
