langsorder:
- 'id'
- 'da'
- 'de'
- 'en'
- 'es'
- 'fr'
- 'it'
- 'hu'
- 'nl'
- 'pl'
- 'pt_BR'
- 'ro'
- 'sl'
- 'sv'
- 'tr'
- 'el'
- 'bg'
- 'ru'
- 'uk'
- 'ar'
- 'fa'
- 'hi'
- 'ko'
- 'ja'
- 'zh_CN'
- 'zh_TW'

langs:
  'ar': 'العربية'
  'bg': 'български'
  'da': 'Dansk'
  'de': 'Deutsch'
  'en': 'English'
  'el': 'Ελληνικά'
  'es': 'Español'
  'fa': 'فارسی'
  'fr': 'Français'
  'hi': 'हिन्दी'
  'hu': 'magyar'
  'id': 'Bahasa Indonesia'
  'it': 'Italiano'
  'ja': '日本語'
  'ko': '한국의'
  'nl': 'Nederlands'
  'pl': 'polski'
  'pt_BR': 'Português Brasil'
  'ro': 'română'
  'ru': 'Русский'
  'sl': 'slovenščina'
  'sv': 'Svenska'
  'tr': 'Türkçe'
  'uk': 'Українська'
  'zh_CN': '简体中文'
  'zh_TW': '繁體中文'

redirects:
  /news: /en/version-history
  /clients: /en/choose-your-wallet
  /about: /en/faq
  /ar/بت-كوين-للهواة: /ar/innovation
  /ar/عن: /ar/faq
  /ar/بت-كوين-للمطورين: /ar/bitcoin-for-developers
  /ar/بت-كوين-للأفراد: /ar/bitcoin-for-individuals
  /ar/إختر-محفظتك: /ar/choose-your-wallet
  /ar/بت-كوين-للأعمال: /ar/bitcoin-for-businesses
  /ar/إختر-محفظتك: /ar/choose-your-wallet
  /ar/مجتمع: /ar/community
  /ar/تطوير: /ar/development
  /ar/تحميل: /ar/download
  /ar/كيف-يعمل: /ar/how-it-works
  /ar/مصادر: /ar/resources
  /ar/إدعم-ألبت-كوين: /ar/support-bitcoin
  /ar/مفردات: /ar/vocabulary
  /ar/تحتاج-أن-تعلم: /ar/you-need-to-know
  /fa/بیت-کوین-برای-علاقه-مندان: /fa/innovation
  /fa/درباره: /fa/faq
  /fa/بیت-کوین-برای-توسعه-دهندگان: /fa/bitcoin-for-developers
  /fa/بیت-کوین-برای-افراد: /fa/bitcoin-for-individuals
  /fa/بیت-کوین-برای-کسب-و-کار: /fa/bitcoin-for-businesses
  /fa/انتخاب-کیف-پول: /fa/choose-your-wallet
  /fa/انجمن: /fa/community
  /fa/توسعه: /fa/development
  /fa/دانلود: /fa/download
  /fa/چگونه-کار-می-کند: /fa/how-it-works
  /fa/منابع: /fa/resources
  /fa/کیف-پولتان-را-ایمن-کنید: /fa/secure-your-wallet
  /fa/حمایت-از-بیت-کوین: /fa/support-bitcoin
  /fa/واژگان: /fa/vocabulary
  /fa/آن-چه-باید-بدانید: /fa/you-need-to-know
  /ru/биткоин-разработчикам: /ru/bitcoin-for-developers
  /ru/биткоин-частным-лицам: /ru/bitcoin-for-individuals
  /ru/биткоин-бизнесу: /ru/bitcoin-for-businesses
  /ru/выберите-свой-кошелек: /ru/choose-your-wallet
  /ru/сообщество: /ru/community
  /ru/разработка: /ru/development
  /ru/загрузки: /ru/download
  /ru/как-это-работает: /ru/how-it-works
  /ru/ресурсы: /ru/resources
  /ru/поддержать-биткоин: /ru/support-bitcoin
  /ru/термины: /ru/vocabulary
  /ru/вам-нужно-знать: /ru/you-need-to-know
  /ru/описание: /ru/faq
  /ru/биткоин-энтузиастам: /ru/innovation
  /tr/bilmelisiniz: /tr/bilmeniz-gerekenler
  /tr/yeni-baslamak: /tr/baslarken
  /en/bitcoin-for-press: /en/press
  /de/ueber: /de/faq
  /en/about: /en/faq
  /es/acerca-de: /es/faq
  /fr/a-propos: /fr/faq
  /it/a-proposito: /it/faq
  /nl/over-bitcoin: /nl/faq
  /pl/o: /pl/faq
  /tr/hakkinda: /tr/sss
  /zh_CN/about: /zh_CN/faq
  /zh_TW/about: /zh_TW/faq
  /de/bitcoin-fuer-enthusiasten: /de/innovation
  /en/bitcoin-for-enthusiasts: /en/innovation
  /es/bitcoin-para-entusiastas: /es/innovacion
  /fr/bitcoin-pour-passionnes: /fr/innovation
  /it/bitcoin-per-appassionati: /it/innovazione
  /nl/bitcoin-voor-liefhebbers: /nl/innovatie
  /pl/bitcoin-dla-entuzjastow: /pl/innowacje
  ## Old releases pages; stop adding to this list after 0.8.2
  /releases/2011/04/27/v0.3.21: /en/release/v0.3.21
  /releases/2011/06/05/v0.3.22: /en/release/v0.3.22
  /releases/2011/06/14/v0.3.23: /en/release/v0.3.23
  /releases/2011/07/08/v0.3.24: /en/release/v0.3.24
  /releases/2011/09/23/v0.4.0: /en/release/v0.4.0
  /releases/2011/11/21/v0.5.0: /en/release/v0.5.0
  /releases/2011/12/15/v0.5.1: /en/release/v0.5.1
  /releases/2012/01/09/v0.5.2: /en/release/v0.5.2
  /releases/2012/03/14/v0.5.3: /en/release/v0.5.3
  /releases/2012/03/16/v0.5.3.1: /en/release/v0.5.3.1
  /releases/2012/03/30/v0.6.0: /en/release/v0.6.0
  /releases/2012/05/04/v0.6.1: /en/release/v0.6.1
  /releases/2012/05/08/v0.6.2: /en/release/v0.6.2
  /releases/2012/06/25/v0.6.3: /en/release/v0.6.3
  /releases/2012/09/17/v0.7.0: /en/release/v0.7.0
  /releases/2012/10/19/v0.7.1: /en/release/v0.7.1
  /releases/2012/12/14/v0.7.2: /en/release/v0.7.2
  /releases/2013/02/19/v0.8.0: /en/release/v0.8.0
  /releases/2013/03/18/v0.8.1: /en/release/v0.8.1
  /releases/2013/05/29/v0.8.2: /en/release/v0.8.2

aliases:
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  gavinandresen: Gavin Andresen
  gmaxwell: Gregory Maxwell
  gwb3: Garland William Binns III
  harding: David Harding
  jgarzik: Jeff Garzik
  laanwj: Wladimir J. van der Laan
  luke-jr: Luke-Jr
  mikehearn: Mike Hearn
  petertodd: Peter Todd
  s_nakamoto: Satoshi Nakamoto
  saivann: Saïvann Carignan
  schildbach: Andreas Schildbach
  sipa: Pieter Wuille
  tcatm: Nils Schneider
  whitj00: Whit Jack
  CodeShark: Eric Lombrozo

safe:        false
port: 4000
base-url:    /

source:      .
destination: ./_site
plugins:     ./_plugins
exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile

future:      true
lsi:         false
highlighter: rouge
pygments:    true
markdown:    kramdown
permalink:   date

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
